# This file was generated by GoReleaser. DO NOT EDIT.
cask "hourglass" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "04ba80bfc4c639d0d0cd259f3c31a04770479c9451447228ccf92990ebab3e4c"
      url "https://github.com/TillmanBuildsTech/hourglass/releases/download/v#{version}/hourglass_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "937c39e03f5e020d596e6821555017f5cabdcadfadc84eec4073d03b61bf57bd"
      url "https://github.com/TillmanBuildsTech/hourglass/releases/download/v#{version}/hourglass_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f3f872d846fd429c6159ea88e4a4333fbe405ae26b8fdf229f1543c664df5c48"
      url "https://github.com/TillmanBuildsTech/hourglass/releases/download/v#{version}/hourglass_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "663ed765db4c598dbf6e73c127bdabc10c81fa3ddd02e3d55d557793e9d86219"
      url "https://github.com/TillmanBuildsTech/hourglass/releases/download/v#{version}/hourglass_linux_arm64.tar.gz"
    end
  end

  name "hourglass"
  desc "Self-hosted web UI for managing Linux and macOS cron jobs"
  homepage "https://github.com/TillmanBuildsTech/hourglass"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hourglass"

  # No zap stanza required

end
