# This file was generated by GoReleaser. DO NOT EDIT.
cask "hourglass" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "5a0fc3e8658ed51daa1a1328d246c9a764ccdd4e99c07b10ecd7b577f8664681"
      url "https://github.com/TillmanBuildsTech/hourglass/releases/download/v#{version}/hourglass_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fa0d323be2798ba70f2809caaae86e9b8c42e6cc10fa96b08539a23e20d5f3ab"
      url "https://github.com/TillmanBuildsTech/hourglass/releases/download/v#{version}/hourglass_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8418c1e68aefaacb99c1fe9bc65e06cacb22d8f79f750bfb6dd99c4c41fc287e"
      url "https://github.com/TillmanBuildsTech/hourglass/releases/download/v#{version}/hourglass_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d1fc253def8d92dadf1b351c9dc2dbad8823229af8dc0c00139b3fdb210389e0"
      url "https://github.com/TillmanBuildsTech/hourglass/releases/download/v#{version}/hourglass_linux_arm64.tar.gz"
    end
  end

  name "hourglass"
  desc "Self-hosted web UI for managing Linux and macOS cron jobs"
  homepage "https://github.com/TillmanBuildsTech/hourglass"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hourglass"

  # No zap stanza required

end
