# This file was generated by GoReleaser. DO NOT EDIT.
cask "hourglass" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "036ac055383000a736337de1e04187ee1dc77db06051fcba9038703eb277eba7"
      url "https://github.com/TillmanBuildsTech/hourglass/releases/download/v#{version}/hourglass_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "81d967622a42fa700009ed52db7a877d6b32d34172f637aac6d8a935b0a7ec5a"
      url "https://github.com/TillmanBuildsTech/hourglass/releases/download/v#{version}/hourglass_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fc35c5f46592af06b78d57657184ff4ac88d146d496bba844a375fe30730fafc"
      url "https://github.com/TillmanBuildsTech/hourglass/releases/download/v#{version}/hourglass_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6c9304eb2456394f21d7550b5c3b678402dded088da78c7882a78ba0be1624b5"
      url "https://github.com/TillmanBuildsTech/hourglass/releases/download/v#{version}/hourglass_linux_arm64.tar.gz"
    end
  end

  name "hourglass"
  desc "Self-hosted web UI for managing Linux and macOS cron jobs"
  homepage "https://github.com/TillmanBuildsTech/hourglass"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hourglass"

  # No zap stanza required

end
